[package]
name = "bravie"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = "0.34.1"
ndarray = "0.17.2"
ndrustfft = "0.6.2"
num-complex = "0.4.6"
plotters = "0.3.7"
rayon = "1.11.0"
roxmltree = "0.21.1"
serde = "1.0.228"
thiserror = "2.0.18"
